[build]
  publish = "public"
  command = "composer install && ./install-php-extensions.sh && php artisan migrate --force"

[context.production.environment]
  PHP_VERSION = "8.1"

[context.production]
  environment = { COMPOSER_ALLOW_SUPERUSER = "1" }